# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atendimento',
            table=None,
        ),
        migrations.AlterModelTable(
            name='carrinho',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cartao',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cliente',
            table=None,
        ),
        migrations.AlterModelTable(
            name='endereco',
            table=None,
        ),
        migrations.AlterModelTable(
            name='estoque',
            table=None,
        ),
        migrations.AlterModelTable(
            name='funcionario',
            table=None,
        ),
        migrations.AlterModelTable(
            name='situacao',
            table=None,
        ),
        migrations.AlterModelTable(
            name='telefone',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tipofuncionario',
            table=None,
        ),
        migrations.AlterModelTable(
            name='trocapontos',
            table=None,
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
