# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_auto_20170510_1448'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atendimento',
            table='modelo_atendimento',
        ),
        migrations.AlterModelTable(
            name='carrinho',
            table='modelo_carrinho',
        ),
        migrations.AlterModelTable(
            name='cartao',
            table='modelo_cartao',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='modelo_cliente',
        ),
        migrations.AlterModelTable(
            name='endereco',
            table='modelo_endereco',
        ),
        migrations.AlterModelTable(
            name='estoque',
            table='modelo_estoque',
        ),
        migrations.AlterModelTable(
            name='funcionario',
            table='modelo_funcionario',
        ),
        migrations.AlterModelTable(
            name='situacao',
            table='modelo_situacao',
        ),
        migrations.AlterModelTable(
            name='telefone',
            table='modelo_telefone',
        ),
        migrations.AlterModelTable(
            name='tipofuncionario',
            table='modelo_tipoFuncionario',
        ),
        migrations.AlterModelTable(
            name='trocapontos',
            table='modelo_trocapontos',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='modelo_usuario',
        ),
    ]
