# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_auto_20170510_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimento',
            old_name='FK_atendimento_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='atendimento',
            old_name='FK_atendimento_funcionario',
            new_name='funcionario',
        ),
        migrations.RenameField(
            model_name='carrinho',
            old_name='FK_carrinho_atendimento',
            new_name='atendimento',
        ),
        migrations.RenameField(
            model_name='carrinho',
            old_name='FK_carrinho_estoque',
            new_name='estoque',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='FK_cliente_cartao',
            new_name='cartao',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='FK_cliente_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='FK_funcionario_situacao',
            new_name='situacao',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='FK_funcionario_tipo_funcionario',
            new_name='tipo_funcionario',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='FK_funcionario_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='trocapontos',
            old_name='FK_trocaPontos_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='trocapontos',
            old_name='FK_trocaPontos_estoque',
            new_name='estoque',
        ),
        migrations.RenameField(
            model_name='trocapontos',
            old_name='FK_trocaPontos_funcionario',
            new_name='funcionario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='FK_usuario_endereco',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='FK_usuario_telefone',
            new_name='telefone',
        ),
    ]
