# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0006_auto_20170511_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='max_pontos',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
