# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0008_auto_20170527_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='max_pontos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='situacao',
            name='descricao',
            field=models.CharField(choices=[('I', 'Inativo'), ('A', 'Ativo')], default=('F', 'Funcionario'), max_length=45),
        ),
        migrations.AlterField(
            model_name='tipofuncionario',
            name='desc_tipo',
            field=models.CharField(choices=[('F', 'Funcionario'), ('G', 'Gerente')], default=('F', 'Funcionario'), max_length=45),
        ),
    ]
