# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0010_auto_20170606_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='valor_Total',
            field=models.FloatField(default=0),
        ),
    ]
