# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-07 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0011_carrinho_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='data_compra',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quant_produtos',
            field=models.IntegerField(null=True),
        ),
    ]
